set -g pane-base-index 0
set -g base-index 0

# Catppuccin Mocha palette
set -g status-style "bg=#1e1e2e,fg=#cdd6f4"
set -g pane-active-border-style "fg=#89b4fa"
set -g pane-border-style "fg=#45475a"
set -g status-left "#[bg=#89b4fa,fg=#1e1e2e,bold] #S "
set -g status-right ""
